services:
  - type: web
    name: auth-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn auth_service.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: auth-service-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: auth-service-redis
          property: connectionString

databases:
  - name: auth-service-db
    databaseName: auth_service_db
    user: auth_service_user
    plan: free

  - name: auth-service-redis
    type: redis
    plan: free
